zotero:
  user_id: ${oc.env:ZOTERO_ID}
  api_key: ${oc.env:ZOTERO_KEY}
  include_path: null # Or set a list of glob patterns, e.g. ["2026/survey/**","2026/reading-group/**"]

email:
  sender: ${oc.env:SENDER}
  receiver: ${oc.env:RECEIVER}
  smtp_server: smtp.qq.com
  smtp_port: 465
  sender_password: ${oc.env:SENDER_PASSWORD}

llm:
  api:
    key: ${oc.env:OPENAI_API_KEY}
    base_url: ${oc.env:OPENAI_API_BASE}
  generation_kwargs:
    model: deepseek-ai/DeepSeek-V3

source:
  arxiv:
    category: ["cs.CL","cs.LG","cs.SE","cs.CR"]
    include_cross_list: true
  openalex:
    venues_path: assets/LLM_Smart_Contract_Venues_Perfect.xlsx
    days: 30
    per_venue_limit: 5

executor:
  debug: ${oc.env:DEBUG,null}
  source: ['arxiv','openalex']
  reranker: api
  skip_sent: true
  sent_history_path: data/sent_papers.json
  
reranker:
  api:
    key: ${oc.env:OPENAI_API_KEY}
    base_url: ${oc.env:OPENAI_API_BASE}
    model: BAAI/bge-m3
